extends: relaxed

yaml-files:
  - '*.yaml'
  - '*.yaml.template'
  - '*.yml'
  - '.yamllint'

ignore:
  - k8s/charts/timeleap-worker/*
  - '*.private/*'
  - '*.private.yaml'

rules:
  indentation:
    spaces: 2

  line-length: disable
