// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AssetPrice is the predicate function for assetprice builders.
type AssetPrice func(*sql.Selector)

// CorrectnessReport is the predicate function for correctnessreport builders.
type CorrectnessReport func(*sql.Selector)

// EventLog is the predicate function for eventlog builders.
type EventLog func(*sql.Selector)

// Signer is the predicate function for signer builders.
type Signer func(*sql.Selector)
