zk:
	GOOS=windows GOARCH=amd64 go build -o bin/zk.windows.amd64.exe main.go
	GOOS=darwin GOARCH=amd64 go build -o bin/zk.darwin.amd64 main.go
	GOOS=darwin GOARCH=arm64 go build -o bin/zk.darwin.arm64 main.go
	GOOS=linux GOARCH=amd64 go build -o bin/zk.linux.amd64 main.go
	GOOS=linux GOARCH=arm64 go build -o bin/zk.linux.arm64 main.go
