{
 "title": "Unchained",
 "description": "Unchained Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img width=\"240px\" src=\"https://kenshi.io/images/logo.typography.svg\">\n\n<p style=\"margin-top: 2em\">\n  Welcome to the Kenshi Unchained dashboard.\n</p>"
   }
  },
  {
   "title": "Ethereum Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"createdAt\", price FROM \"AssetPrice\" ORDER BY \"createdAt\""
    }
   ]
  },
  {
   "title": "Peer Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n    \"AssetPrice\".\"createdAt\",\n    COUNT(\"SignersOnAssetPrice\".\"signerId\") as \"signers\"\nFROM \n    \"AssetPrice\"\nLEFT JOIN \n    \"SignersOnAssetPrice\" ON \"AssetPrice\".\"id\" = \"SignersOnAssetPrice\".\"assetPriceId\"\nGROUP BY \n    \"AssetPrice\".\"createdAt\"\nORDER BY \n    \"AssetPrice\".\"createdAt\"\n"
    }
   ]
  },
  { "title": "Raw Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Latest Verified Data",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \n    \"AssetPrice\".\"block\", \n    \"AssetPrice\".\"price\", \n    COUNT(\"SignersOnAssetPrice\".\"signerId\") as \"signers\",\n    \"AssetPrice\".\"signature\"\nFROM \n    \"AssetPrice\"\nLEFT JOIN \n    \"SignersOnAssetPrice\" ON \"AssetPrice\".\"id\" = \"SignersOnAssetPrice\".\"assetPriceId\"\nGROUP BY \n    \"AssetPrice\".\"block\", \"AssetPrice\".\"price\", \"AssetPrice\".\"signature\"\nORDER BY \n    \"AssetPrice\".\"block\" DESC\n"
    }
   ]
  }
 ]
}