// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KenshiTech/unchained/ent/assetprice"
	"github.com/KenshiTech/unchained/ent/predicate"
	"github.com/KenshiTech/unchained/ent/signer"
)

// SignerUpdate is the builder for updating Signer entities.
type SignerUpdate struct {
	config
	hooks    []Hook
	mutation *SignerMutation
}

// Where appends a list predicates to the SignerUpdate builder.
func (su *SignerUpdate) Where(ps ...predicate.Signer) *SignerUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SignerUpdate) SetName(s string) *SignerUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SignerUpdate) SetNillableName(s *string) *SignerUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetKey sets the "key" field.
func (su *SignerUpdate) SetKey(b []byte) *SignerUpdate {
	su.mutation.SetKey(b)
	return su
}

// SetPoints sets the "points" field.
func (su *SignerUpdate) SetPoints(i int64) *SignerUpdate {
	su.mutation.ResetPoints()
	su.mutation.SetPoints(i)
	return su
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (su *SignerUpdate) SetNillablePoints(i *int64) *SignerUpdate {
	if i != nil {
		su.SetPoints(*i)
	}
	return su
}

// AddPoints adds i to the "points" field.
func (su *SignerUpdate) AddPoints(i int64) *SignerUpdate {
	su.mutation.AddPoints(i)
	return su
}

// AddAssetPriceIDs adds the "assetPrice" edge to the AssetPrice entity by IDs.
func (su *SignerUpdate) AddAssetPriceIDs(ids ...int) *SignerUpdate {
	su.mutation.AddAssetPriceIDs(ids...)
	return su
}

// AddAssetPrice adds the "assetPrice" edges to the AssetPrice entity.
func (su *SignerUpdate) AddAssetPrice(a ...*AssetPrice) *SignerUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return su.AddAssetPriceIDs(ids...)
}

// Mutation returns the SignerMutation object of the builder.
func (su *SignerUpdate) Mutation() *SignerMutation {
	return su.mutation
}

// ClearAssetPrice clears all "assetPrice" edges to the AssetPrice entity.
func (su *SignerUpdate) ClearAssetPrice() *SignerUpdate {
	su.mutation.ClearAssetPrice()
	return su
}

// RemoveAssetPriceIDs removes the "assetPrice" edge to AssetPrice entities by IDs.
func (su *SignerUpdate) RemoveAssetPriceIDs(ids ...int) *SignerUpdate {
	su.mutation.RemoveAssetPriceIDs(ids...)
	return su
}

// RemoveAssetPrice removes "assetPrice" edges to AssetPrice entities.
func (su *SignerUpdate) RemoveAssetPrice(a ...*AssetPrice) *SignerUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return su.RemoveAssetPriceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SignerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SignerUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SignerUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SignerUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SignerUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := signer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Signer.name": %w`, err)}
		}
	}
	if v, ok := su.mutation.Key(); ok {
		if err := signer.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Signer.key": %w`, err)}
		}
	}
	return nil
}

func (su *SignerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(signer.Table, signer.Columns, sqlgraph.NewFieldSpec(signer.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(signer.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Key(); ok {
		_spec.SetField(signer.FieldKey, field.TypeBytes, value)
	}
	if value, ok := su.mutation.Points(); ok {
		_spec.SetField(signer.FieldPoints, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedPoints(); ok {
		_spec.AddField(signer.FieldPoints, field.TypeInt64, value)
	}
	if su.mutation.AssetPriceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   signer.AssetPriceTable,
			Columns: signer.AssetPricePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetprice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedAssetPriceIDs(); len(nodes) > 0 && !su.mutation.AssetPriceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   signer.AssetPriceTable,
			Columns: signer.AssetPricePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.AssetPriceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   signer.AssetPriceTable,
			Columns: signer.AssetPricePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SignerUpdateOne is the builder for updating a single Signer entity.
type SignerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignerMutation
}

// SetName sets the "name" field.
func (suo *SignerUpdateOne) SetName(s string) *SignerUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SignerUpdateOne) SetNillableName(s *string) *SignerUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetKey sets the "key" field.
func (suo *SignerUpdateOne) SetKey(b []byte) *SignerUpdateOne {
	suo.mutation.SetKey(b)
	return suo
}

// SetPoints sets the "points" field.
func (suo *SignerUpdateOne) SetPoints(i int64) *SignerUpdateOne {
	suo.mutation.ResetPoints()
	suo.mutation.SetPoints(i)
	return suo
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (suo *SignerUpdateOne) SetNillablePoints(i *int64) *SignerUpdateOne {
	if i != nil {
		suo.SetPoints(*i)
	}
	return suo
}

// AddPoints adds i to the "points" field.
func (suo *SignerUpdateOne) AddPoints(i int64) *SignerUpdateOne {
	suo.mutation.AddPoints(i)
	return suo
}

// AddAssetPriceIDs adds the "assetPrice" edge to the AssetPrice entity by IDs.
func (suo *SignerUpdateOne) AddAssetPriceIDs(ids ...int) *SignerUpdateOne {
	suo.mutation.AddAssetPriceIDs(ids...)
	return suo
}

// AddAssetPrice adds the "assetPrice" edges to the AssetPrice entity.
func (suo *SignerUpdateOne) AddAssetPrice(a ...*AssetPrice) *SignerUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return suo.AddAssetPriceIDs(ids...)
}

// Mutation returns the SignerMutation object of the builder.
func (suo *SignerUpdateOne) Mutation() *SignerMutation {
	return suo.mutation
}

// ClearAssetPrice clears all "assetPrice" edges to the AssetPrice entity.
func (suo *SignerUpdateOne) ClearAssetPrice() *SignerUpdateOne {
	suo.mutation.ClearAssetPrice()
	return suo
}

// RemoveAssetPriceIDs removes the "assetPrice" edge to AssetPrice entities by IDs.
func (suo *SignerUpdateOne) RemoveAssetPriceIDs(ids ...int) *SignerUpdateOne {
	suo.mutation.RemoveAssetPriceIDs(ids...)
	return suo
}

// RemoveAssetPrice removes "assetPrice" edges to AssetPrice entities.
func (suo *SignerUpdateOne) RemoveAssetPrice(a ...*AssetPrice) *SignerUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return suo.RemoveAssetPriceIDs(ids...)
}

// Where appends a list predicates to the SignerUpdate builder.
func (suo *SignerUpdateOne) Where(ps ...predicate.Signer) *SignerUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SignerUpdateOne) Select(field string, fields ...string) *SignerUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Signer entity.
func (suo *SignerUpdateOne) Save(ctx context.Context) (*Signer, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SignerUpdateOne) SaveX(ctx context.Context) *Signer {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SignerUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SignerUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SignerUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := signer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Signer.name": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Key(); ok {
		if err := signer.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Signer.key": %w`, err)}
		}
	}
	return nil
}

func (suo *SignerUpdateOne) sqlSave(ctx context.Context) (_node *Signer, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signer.Table, signer.Columns, sqlgraph.NewFieldSpec(signer.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Signer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signer.FieldID)
		for _, f := range fields {
			if !signer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(signer.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Key(); ok {
		_spec.SetField(signer.FieldKey, field.TypeBytes, value)
	}
	if value, ok := suo.mutation.Points(); ok {
		_spec.SetField(signer.FieldPoints, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedPoints(); ok {
		_spec.AddField(signer.FieldPoints, field.TypeInt64, value)
	}
	if suo.mutation.AssetPriceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   signer.AssetPriceTable,
			Columns: signer.AssetPricePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetprice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedAssetPriceIDs(); len(nodes) > 0 && !suo.mutation.AssetPriceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   signer.AssetPriceTable,
			Columns: signer.AssetPricePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.AssetPriceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   signer.AssetPriceTable,
			Columns: signer.AssetPricePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetprice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Signer{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
